const $=s=>document.querySelector(s);const TOKEN_KEY='lcr_paid_access_token';const BUNDLE_KEY='lcr_paid_bundle';let data=null,current=0,answers={};
function show(id){['advLoading','advIntro','advQuestion','advSubmit','advResult'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function saveProgress(){localStorage.setItem('lcr_adv_progress',JSON.stringify({answers,current}))}
function loadProgress(){try{const x=JSON.parse(localStorage.getItem('lcr_adv_progress')||'null');if(x){answers=x.answers||{};current=Math.max(0,Math.min(19,Number(x.current||0)))}}catch{}}
async function init(){const token=localStorage.getItem(TOKEN_KEY);if(!token){location.href='/acesso/passaporte';return}try{const cached=JSON.parse(localStorage.getItem(BUNDLE_KEY)||'null');if(cached?.data?.advanced){return renderExisting(cached.data.advanced)}const r=await fetch('/advanced-data.v1.json',{cache:'force-cache'});if(!r.ok)throw new Error('Prova indisponível');data=await r.json();loadProgress();show('advIntro')}catch(e){$('#advLoading').innerHTML=`<span class="kicker">ERRO</span><h1>${esc(e.message)}</h1><a class="cta" href="/acesso/passaporte">VOLTAR AO PASSAPORTE</a>`}}
$('#startAdvanced').addEventListener('click',()=>{show('advQuestion');renderQuestion()});
function renderQuestion(){const q=data.questions[current];$('#advCategory').textContent=q.category;$('#advPrompt').textContent=q.prompt;$('#advCount').textContent=`${current+1}/20`;$('#advBar').style.width=`${((current+1)/20)*100}%`;$('#advOptions').innerHTML=q.options.map(o=>`<button class="adv-option ${answers[q.code]===o.key?'selected':''}" data-key="${o.key}"><span>${o.key}</span><b>${esc(o.label)}</b></button>`).join('');$('#advOptions').querySelectorAll('.adv-option').forEach(b=>b.addEventListener('click',()=>{answers[q.code]=b.dataset.key;saveProgress();$('#advOptions').querySelectorAll('.adv-option').forEach(x=>x.classList.toggle('selected',x===b))}));$('#advBack').disabled=current===0}
$('#advNext').addEventListener('click',()=>{const q=data.questions[current];if(!answers[q.code]){alert('Escolha uma resposta para continuar.');return}if(current>=data.questions.length-1){show('advSubmit');return}current++;saveProgress();renderQuestion();window.scrollTo({top:0,behavior:'smooth'})});
$('#advBack').addEventListener('click',()=>{if(current>0){current--;saveProgress();renderQuestion()}});
$('#returnAdvanced').addEventListener('click',()=>{show('advQuestion');renderQuestion()});
$('#finishAdvanced').addEventListener('click',async()=>{const missing=data.questions.filter(q=>!answers[q.code]);if(missing.length){$('#advError').textContent=`Ainda faltam ${missing.length} respostas.`;return}const btn=$('#finishAdvanced');btn.disabled=true;btn.textContent='VALIDANDO...';$('#advError').textContent='';try{const token=localStorage.getItem(TOKEN_KEY);const payload=data.questions.map(q=>({code:q.code,answer:answers[q.code]}));const r=await LCR_API.rpc('lcr_submit_advanced',{p_access_token:token,p_answers:payload},{retries:2,timeoutMs:10000});localStorage.removeItem('lcr_adv_progress');try{const cached=JSON.parse(localStorage.getItem(BUNDLE_KEY)||'null');if(cached?.data){cached.data.advanced={score:r.score,correctAnswers:r.correctAnswers,totalQuestions:r.totalQuestions,completedAt:r.completedAt};cached.savedAt=Date.now();localStorage.setItem(BUNDLE_KEY,JSON.stringify(cached))}}catch{}renderResult(r)}catch(e){$('#advError').textContent=e.message}finally{btn.disabled=false;btn.textContent='VALIDAR MINHA PROVA'}})
function renderExisting(a){show('advResult');$('#advScore').textContent=`${a.score}/100`;$('#advResultTitle').textContent='Sua Prova Avançada já foi registrada.';$('#advResultCopy').textContent=`${a.correctAnswers}/${a.totalQuestions} acertos. O resultado oficial fica vinculado ao seu Passaporte.`;$('#advCorrections').innerHTML=''}
function renderResult(r){show('advResult');$('#advScore').textContent=`${r.score}/100`;let title='Prova registrada.';let copy='Você concluiu a segunda etapa da Temporada Fundadores.';if(r.score>=90){title='Nível de Guardião.';copy='Seu desempenho avançado foi excepcional. Você provou domínio forte dos fundamentos e da doutrina.'}else if(r.score>=70){title='Católico Raiz confirmado.';copy='Você sustentou um bom nível mesmo em perguntas mais difíceis.'}else if(r.score>=50){title='Boa base, com pontos claros para evoluir.';copy='Use as correções abaixo como mapa para sua próxima evolução.'}else{title='Agora você sabe exatamente onde estudar.';copy='A prova avançada mostrou os pontos que mais merecem revisão.'}$('#advResultTitle').textContent=title;$('#advResultCopy').textContent=copy;$('#advCorrections').innerHTML=(r.details||[]).map(x=>`<article class="correction ${x.isCorrect?'good':'bad'}"><b>${x.position}. ${esc(x.prompt)}</b><p>${x.isCorrect?'✓ Resposta correta.':`Sua resposta: ${esc(x.selectedOption||'—')} • Correta: ${esc(x.correctOption)}`}</p><p>${esc(x.explanation||'')}</p>${x.referenceText?`<small>${esc(x.referenceText)}</small>`:''}</article>`).join('')}
init();