const LCR_AUTH_KEY='lcr_auth_session';
const authCfg=window.LCR_CONFIG;
function readStoredSession(){try{return JSON.parse(localStorage.getItem(LCR_AUTH_KEY)||'null')}catch{return null}}
function normalizeSession(data){if(!data?.access_token||!data?.refresh_token)return null;const expires_in=Number(data.expires_in||3600);return{...data,expires_in,expires_at:Number(data.expires_at||Math.floor(Date.now()/1000)+expires_in)}}
function storeSession(session){const normalized=normalizeSession(session);if(normalized){localStorage.setItem(LCR_AUTH_KEY,JSON.stringify(normalized));return normalized}localStorage.removeItem(LCR_AUTH_KEY);return null}
function authHeaders(token){return{apikey:authCfg.supabaseKey,Authorization:`Bearer ${token||authCfg.supabaseKey}`,'Content-Type':'application/json'}}
async function authRequest(path,{method='POST',body,token}={}){const r=await fetch(`${authCfg.supabaseUrl}/auth/v1${path}`,{method,headers:authHeaders(token),body:body?JSON.stringify(body):undefined});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||'Não foi possível concluir o acesso.');return data}
async function refreshSession(session=readStoredSession()){if(!session?.refresh_token)return null;try{const next=await authRequest('/token?grant_type=refresh_token',{body:{refresh_token:session.refresh_token}});return storeSession(next)}catch{storeSession(null);return null}}
async function getSession(){let session=readStoredSession();if(!session)return null;const expiresAt=Number(session.expires_at||0)*1000;if(!expiresAt||expiresAt-Date.now()<60000)session=await refreshSession(session);return session}
async function getUser(){const session=await getSession();if(!session)return null;try{return await authRequest('/user',{method:'GET',token:session.access_token})}catch{return null}}
async function signUp({email,password,name,nickname}){const redirect=encodeURIComponent(`${location.origin}/login`);const data=await authRequest(`/signup?redirect_to=${redirect}`,{body:{email:email.trim().toLowerCase(),password,data:{name,nickname}}});const session=storeSession(data);return{...data,session}}
async function signIn(email,password){const data=await authRequest('/token?grant_type=password',{body:{email:email.trim().toLowerCase(),password}});storeSession(data);return data}
async function signOut(){const session=await getSession();if(session){try{await authRequest('/logout',{token:session.access_token,body:{scope:'local'}})}catch{}}storeSession(null)}
async function recover(email){const redirect=encodeURIComponent(`${location.origin}/login?mode=recovery`);return authRequest(`/recover?redirect_to=${redirect}`,{body:{email:email.trim().toLowerCase()}})}
async function updatePassword(password){const session=await getSession();if(!session)throw new Error('Sessão expirada. Solicite um novo link.');return authRequest('/user',{method:'PUT',token:session.access_token,body:{password}})}
function consumeHashSession(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const access_token=hash.get('access_token'),refresh_token=hash.get('refresh_token');if(access_token&&refresh_token){const expires_in=Number(hash.get('expires_in')||3600);storeSession({access_token,refresh_token,expires_in,expires_at:Math.floor(Date.now()/1000)+expires_in,token_type:hash.get('token_type')||'bearer',user:null});history.replaceState({},'',location.pathname+location.search);return true}return false}
window.LCR_AUTH={getSession,getUser,signUp,signIn,signOut,recover,updatePassword,consumeHashSession,readStoredSession};