const $=s=>document.querySelector(s);const ACCESS_TOKEN_KEY='lcr_paid_access_token';const BUNDLE_KEY='lcr_paid_bundle';const CACHE_MS=30*60*1000;let bundle=null;
function showOnly(id){['gate','loading','area'].forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id))}
function saveBundle(data){bundle=data;localStorage.setItem(ACCESS_TOKEN_KEY,data.accessToken);localStorage.setItem(BUNDLE_KEY,JSON.stringify({savedAt:Date.now(),data}))}
function getCached(){try{const x=JSON.parse(localStorage.getItem(BUNDLE_KEY)||'null');if(x&&Date.now()-x.savedAt<CACHE_MS)return x.data}catch{}return null}
function levelFromScore(score){if(score>=90)return['Guardião da Fé','🛡️'];if(score>=70)return['Católico Raiz','🔥'];if(score>=50)return['Católico Praticante','⚔️'];return['Discípulo em Formação','🌱']}
function fmtTime(s){s=Number(s||0);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadByToken(token){showOnly('loading');try{const d=await LCR_API.rpc('lcr_paid_delivery_by_token',{p_access_token:token},{retries:2});if(!d?.paid)throw new Error('Acesso não encontrado ou pagamento não está mais ativo.');if(!d.linked||!d.hasResult)throw new Error('Pagamento confirmado, mas não localizamos uma prova concluída com esse WhatsApp.');saveBundle(d);render(d)}catch(e){localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);showOnly('gate');$('#accessError').textContent=e.message}}
$('#accessForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const btn=e.submitter;$('#accessError').textContent='';btn.disabled=true;btn.textContent='VALIDANDO...';try{const d=await LCR_API.rpc('lcr_paid_delivery',{p_whatsapp:fd.get('whatsapp'),p_email:fd.get('email')},{retries:2});if(!d?.paid)throw new Error('Pagamento aprovado ainda não localizado. Confira os dados da compra e tente novamente em alguns instantes.');if(!d.linked)throw new Error('Pagamento encontrado, mas o WhatsApp da compra não corresponde a uma participação do quiz.');if(!d.hasResult)throw new Error('Pagamento encontrado, mas não existe uma prova concluída para esse WhatsApp.');saveBundle(d);render(d)}catch(err){$('#accessError').textContent=err.message}finally{btn.disabled=false;btn.textContent='LIBERAR MEU PASSAPORTE'}})
function render(d){bundle=d;const r=d.result||{};const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||d.customerName||'Participante';showOnly('area');$('#memberName').textContent=name;$('#passportName').textContent=name;$('#passportLevel').textContent=`${icon} ${level}`;$('#passportScore').textContent=`${r.score||0}/100`;$('#passportCode').textContent=`#${r.proofCode||'—'}`;$('#scoreBig').textContent=`${r.score||0}/100`;$('#correctBig').textContent=`${r.correctAnswers||0}/${r.totalQuestions||10}`;$('#timeBig').textContent=`Tempo ${fmtTime(r.durationSeconds)}`;$('#scoreMeter').style.width=`${Math.max(0,Math.min(100,Number(r.score||0)))}%`;renderCategories(r.categoryStats||[]);renderAnswers(d.answers||[]);renderRoute(r.categoryStats||[],d.answers||[]);if(d.advanced){$('#advancedBtn').classList.add('hidden');$('#advancedDone').classList.remove('hidden');$('#advancedDone').textContent=`Prova Avançada concluída: ${d.advanced.score}/100 • ${d.advanced.correctAnswers}/${d.advanced.totalQuestions} acertos`}}
function renderCategories(stats){$('#categoryBars').innerHTML=stats.map(x=>`<div class="category-row"><span>${esc(x.category)}</span><div><i style="width:${Number(x.percent)||0}%"></i></div><b>${Number(x.percent)||0}%</b></div>`).join('')||'<p class="muted">Sem dados suficientes.</p>'}
function renderAnswers(list){$('#answerReview').innerHTML=list.map(x=>`<details class="review-item ${x.isCorrect?'good':'bad'}"><summary><span class="num">${x.position}</span><b>${esc(x.prompt)}</b><em>${x.isCorrect?'✓':'×'}</em></summary><div class="review-body"><p><strong>Sua resposta:</strong> ${esc(x.selectedLabel||x.selectedOption||'—')}</p>${x.isCorrect?'':`<p><strong>Resposta correta:</strong> ${esc(x.correctLabel||x.correctOption)}</p>`}<p>${esc(x.explanation)}</p>${x.referenceText?`<p class="ref">${esc(x.referenceText)}</p>`:''}</div></details>`).join('')}
function renderRoute(stats,answers){const sorted=[...stats].sort((a,b)=>Number(a.percent)-Number(b.percent));const weak=sorted[0]?.category||'Fundamentos da Fé';const strong=[...stats].sort((a,b)=>Number(b.percent)-Number(a.percent))[0]?.category||'seus melhores temas';const refs=answers.filter(x=>!x.isCorrect&&x.referenceText).slice(0,3).map(x=>x.referenceText);$('#routeIntro').textContent=`Seu ponto de atenção principal foi ${weak}. Sua maior força apareceu em ${strong}. A rota abaixo usa exatamente esse contraste.`;const days=[['Diagnóstico sem consulta',`Explique com suas palavras o que você entende sobre ${weak}. Depois compare com o gabarito comentado.`],['Base doutrinal',refs[0]?`Leia e revise: ${refs[0]}. Anote 3 ideias que você não lembrava.`:`Revise as referências das questões de ${weak} no gabarito comentado.`],['Memória ativa',`Feche o material e escreva 5 pontos sobre ${weak} sem consultar nada. Só depois confira.`],['Ensine para fixar',`Explique um conceito de ${weak} em voz alta como se estivesse ensinando alguém da família.`],['Conecte com sua força',`Relacione ${weak} com ${strong}. Procure uma ligação entre os dois temas na fé católica.`],['Revisão dos erros',`Volte apenas às questões que você errou. Leia a explicação e a referência, sem refazer tudo.`],['Prova de evolução','Faça a Prova Avançada de 20 questões e registre sua nova pontuação.']];$('#routeDays').innerHTML=days.map((x,i)=>`<div class="route-day"><b>DIA ${i+1}</b><div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div></div>`).join('')}
function drawPassport(){if(!bundle)return;const r=bundle.result;const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||bundle.customerName||'Participante';const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d');const grad=ctx.createLinearGradient(0,0,1080,1350);grad.addColorStop(0,'#071c16');grad.addColorStop(1,'#174d37');ctx.fillStyle=grad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#58cc02';roundRect(ctx,70,70,120,120,28);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 64px system-ui';ctx.textAlign='center';ctx.fillText('✠',130,153);ctx.textAlign='left';ctx.fillStyle='#b9cbbf';ctx.font='700 28px system-ui';ctx.fillText('LIGA DO CATÓLICO RAIZ',230,108);ctx.fillStyle='#fff';ctx.font='900 44px system-ui';ctx.fillText('PASSAPORTE OFICIAL',230,160);ctx.fillStyle='#e2b93b';ctx.font='800 27px system-ui';ctx.fillText('TEMPORADA FUNDADORES',70,300);ctx.fillStyle='#fff';ctx.font='900 70px system-ui';wrapText(ctx,name,70,405,940,82);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('NÍVEL CONQUISTADO',70,600);ctx.fillStyle='#fff';ctx.font='900 52px system-ui';ctx.fillText(`${icon} ${level}`,70,662);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('PONTUAÇÃO OFICIAL',70,770);ctx.fillStyle='#fff';ctx.font='900 66px system-ui';ctx.fillText(`${r.score||0}/100`,70,842);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('CÓDIGO DA PROVA',70,955);ctx.fillStyle='#fff';ctx.font='900 45px system-ui';ctx.fillText(`#${r.proofCode||'—'}`,70,1014);ctx.fillStyle='#58cc02';ctx.fillRect(70,1130,940,4);ctx.fillStyle='#b9cbbf';ctx.font='700 24px system-ui';ctx.fillText('PAY TO PROVE • PROVA REGISTRADA',70,1200);ctx.fillStyle='#fff';ctx.font='700 21px system-ui';ctx.fillText('Temporada Fundadores',70,1245);return c}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=String(text).split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=word+' ';y+=lineHeight}else line=test}ctx.fillText(line,x,y)}
$('#downloadPassport').addEventListener('click',()=>{const c=drawPassport();if(!c)return;const a=document.createElement('a');a.download='passaporte-catolico-raiz.png';a.href=c.toDataURL('image/png');a.click()});
$('#sharePassport').addEventListener('click',async()=>{const c=drawPassport();if(!c)return;c.toBlob(async blob=>{try{const file=new File([blob],'passaporte-catolico-raiz.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({title:'Meu Passaporte Católico Raiz',text:'Eu provei meu nível na Liga do Católico Raiz.',files:[file]});else{await navigator.clipboard.writeText(location.origin);alert('Link copiado. Salve o Passaporte e compartilhe junto!')}}catch{}},'image/png')});
$('#logoutAccess').addEventListener('click',()=>{localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);location.reload()});
(async()=>{const cached=getCached();if(cached?.paid&&cached?.hasResult)return render(cached);const token=localStorage.getItem(ACCESS_TOKEN_KEY);if(token)return loadByToken(token);showOnly('gate')})();