const $=s=>document.querySelector(s);const ACCESS_TOKEN_KEY='lcr_paid_access_token';const BUNDLE_KEY='lcr_paid_bundle';const CACHE_MS=30*60*1000;let bundle=null;
function showOnly(id){['gate','loading','area'].forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id))}
function saveBundle(data){bundle=data;localStorage.setItem(ACCESS_TOKEN_KEY,data.accessToken);localStorage.setItem(BUNDLE_KEY,JSON.stringify({savedAt:Date.now(),data}))}
function getCached(){try{const x=JSON.parse(localStorage.getItem(BUNDLE_KEY)||'null');if(x&&Date.now()-x.savedAt<CACHE_MS)return x.data}catch{}return null}
function levelFromScore(score){if(score>=90)return['Guardião da Fé','🛡️'];if(score>=70)return['Católico Raiz','🔥'];if(score>=50)return['Católico Praticante','⚔️'];return['Discípulo em Formação','🌱']}
function fmtTime(s){s=Number(s||0);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadByToken(token){showOnly('loading');try{const d=await LCR_API.rpc('lcr_paid_delivery_by_token',{p_access_token:token},{retries:2});if(!d?.paid)throw new Error('Acesso não encontrado ou pagamento não está mais ativo.');if(!d.linked||!d.hasResult)throw new Error('Pagamento confirmado, mas não localizamos uma prova concluída vinculada à compra.');saveBundle(d);render(d)}catch(e){localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);showOnly('gate');$('#accessError').textContent=e.message}}
$('#accessForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const btn=e.submitter;$('#accessError').textContent='';btn.disabled=true;btn.textContent='VALIDANDO...';try{const d=await LCR_API.rpc('lcr_paid_delivery_by_email',{p_email:fd.get('email')},{retries:2});if(!d?.paid)throw new Error('Pagamento aprovado ainda não localizado para este e-mail. Confira o e-mail usado na GG Checkout e tente novamente.');if(!d.linked||!d.hasResult)throw new Error('Pagamento confirmado, mas ainda não localizamos uma prova concluída vinculada ao nome da compra.');saveBundle(d);render(d)}catch(err){$('#accessError').textContent=err.message}finally{btn.disabled=false;btn.textContent='LIBERAR MEU PASSAPORTE'}})
function render(d){bundle=d;const r=d.result||{};const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||d.customerName||'Participante';showOnly('area');$('#memberName').textContent=name;$('#passportName').textContent=name;$('#passportLevel').textContent=`${icon} ${level}`;$('#passportScore').textContent=`${r.score||0}/100`;$('#passportCode').textContent=`#${r.proofCode||'—'}`;$('#scoreBig').textContent=`${r.score||0}/100`;$('#correctBig').textContent=`${r.correctAnswers||0}/${r.totalQuestions||10}`;$('#timeBig').textContent=`Tempo ${fmtTime(r.durationSeconds)}`;$('#scoreMeter').style.width=`${Math.max(0,Math.min(100,Number(r.score||0)))}%`;renderCategories(r.categoryStats||[]);renderAnswers(d.answers||[]);renderRoute(r.categoryStats||[],d.answers||[])}
function renderCategories(stats){$('#categoryBars').innerHTML=stats.map(x=>`<div class="category-row"><span>${esc(x.category)}</span><div><i style="width:${Number(x.percent)||0}%"></i></div><b>${Number(x.percent)||0}%</b></div>`).join('')||'<p class="muted">Sem dados suficientes.</p>'}
function renderAnswers(list){$('#answerReview').innerHTML=list.map(x=>`<details class="review-item ${x.isCorrect?'good':'bad'}"><summary><span class="num">${x.position}</span><b>${esc(x.prompt)}</b><em>${x.isCorrect?'✓':'×'}</em></summary><div class="review-body"><p><strong>Sua resposta:</strong> ${esc(x.selectedLabel||x.selectedOption||'—')}</p>${x.isCorrect?'':`<p><strong>Resposta correta:</strong> ${esc(x.correctLabel||x.correctOption)}</p>`}<p>${esc(x.explanation)}</p>${x.referenceText?`<p class="ref">${esc(x.referenceText)}</p>`:''}</div></details>`).join('')}
function renderRoute(stats,answers){const sorted=[...stats].sort((a,b)=>Number(a.percent)-Number(b.percent));const weak=sorted[0]?.category||'Fundamentos da Fé';const strong=[...stats].sort((a,b)=>Number(b.percent)-Number(a.percent))[0]?.category||'seus melhores temas';$('#routeIntro').textContent=`Seu ponto de atenção principal foi ${weak}. Sua maior força apareceu em ${strong}.`;const days=[['Diagnóstico',`Revise ${weak}.`],['Base doutrinal','Leia o gabarito comentado.'],['Memória ativa',`Escreva 5 pontos sobre ${weak} sem consultar.`],['Ensine para fixar',`Explique um conceito de ${weak} em voz alta.`],['Conecte com sua força',`Relacione ${weak} com ${strong}.`],['Revisão dos erros','Volte às questões que você errou.'],['Prova de evolução','Faça a Prova Avançada.']];$('#routeDays').innerHTML=days.map((x,i)=>`<div class="route-day"><b>DIA ${i+1}</b><div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div></div>`).join('')}
function drawPassport(){if(!bundle)return;const r=bundle.result;const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||bundle.customerName||'Participante';const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d');const grad=ctx.createLinearGradient(0,0,1080,1350);grad.addColorStop(0,'#071c16');grad.addColorStop(1,'#174d37');ctx.fillStyle=grad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='900 70px system-ui';ctx.fillText(name,70,405);ctx.font='900 52px system-ui';ctx.fillText(`${icon} ${level}`,70,662);ctx.font='900 66px system-ui';ctx.fillText(`${r.score||0}/100`,70,842);ctx.font='900 45px system-ui';ctx.fillText(`#${r.proofCode||'—'}`,70,1014);return c}
$('#downloadPassport').addEventListener('click',()=>{const c=drawPassport();if(!c)return;const a=document.createElement('a');a.download='passaporte-catolico-raiz.png';a.href=c.toDataURL('image/png');a.click()});$('#sharePassport').addEventListener('click',async()=>{const c=drawPassport();if(!c)return;c.toBlob(async blob=>{try{const file=new File([blob],'passaporte-catolico-raiz.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({title:'Meu Passaporte Católico Raiz',files:[file]})}catch{}},'image/png')});$('#logoutAccess').addEventListener('click',()=>{localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);location.reload()});(async()=>{const cached=getCached();if(cached?.paid&&cached?.hasResult)return render(cached);const token=localStorage.getItem(ACCESS_TOKEN_KEY);if(token)return loadByToken(token);showOnly('gate')})();