const $=s=>document.querySelector(s);const ACCESS_TOKEN_KEY='lcr_paid_access_token';const BUNDLE_KEY='lcr_paid_bundle_v2';const EMAIL_KEY='lcr_paid_email';const CACHE_MS=15*60*1000;let bundle=null;
function showOnly(id){['gate','loading','area'].forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id))}
function saveBundle(data,email){bundle=data;if(data.accessToken)localStorage.setItem(ACCESS_TOKEN_KEY,data.accessToken);if(email||data.customerEmail)localStorage.setItem(EMAIL_KEY,String(email||data.customerEmail).trim().toLowerCase());localStorage.setItem(BUNDLE_KEY,JSON.stringify({savedAt:Date.now(),data}))}
function getCached(){try{const x=JSON.parse(localStorage.getItem(BUNDLE_KEY)||'null');if(x&&Date.now()-x.savedAt<CACHE_MS)return x.data}catch{}return null}
function getLastAttemptToken(){try{const q=new URLSearchParams(location.search).get('t');if(q)return q;for(const store of [localStorage,sessionStorage]){const raw=store.getItem('lcr_last_result');if(!raw)continue;const parsed=JSON.parse(raw);if(parsed?.token)return parsed.token}}catch{}return null}
function levelFromScore(score){if(score>=90)return['Guardião da Fé','🛡️'];if(score>=70)return['Católico Raiz','🔥'];if(score>=50)return['Católico Praticante','⚔️'];return['Discípulo em Formação','🌱']}
function fmtTime(s){s=Number(s||0);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadByToken(token){showOnly('loading');try{const d=await LCR_API.rpc('lcr_paid_delivery_by_token',{p_access_token:token},{retries:2});if(!d?.paid)throw new Error('Acesso não encontrado ou pagamento não está mais ativo.');saveBundle(d);d.hasResult?render(d):renderPaidOnly(d)}catch(e){const cached=getCached();if(cached?.paid)return cached.hasResult?render(cached):renderPaidOnly(cached);localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);showOnly('gate');$('#accessError').textContent=e.message}}
async function linkEmailToAttempt(email,attemptToken){if(!email||!attemptToken)return null;try{return await LCR_API.rpc('lcr_paid_delivery_by_email_attempt',{p_email:email,p_attempt_token:attemptToken},{retries:2})}catch{return null}}
$('#accessForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const btn=e.submitter;$('#accessError').textContent='';btn.disabled=true;btn.textContent='VALIDANDO...';try{const email=String(fd.get('email')||'').trim().toLowerCase();localStorage.setItem(EMAIL_KEY,email);const attemptToken=getLastAttemptToken();let d=await linkEmailToAttempt(email,attemptToken);if(!d?.paid)d=await LCR_API.rpc('lcr_paid_delivery_by_email',{p_email:email},{retries:2});if(!d?.paid)throw new Error('Pagamento aprovado ainda não localizado para este e-mail. Confira o e-mail usado na GG Checkout e tente novamente.');saveBundle(d,email);d.hasResult?render(d):renderPaidOnly(d)}catch(err){$('#accessError').textContent=err.message}finally{btn.disabled=false;btn.textContent='ACESSAR MEU RESULTADO COMPLETO'}})
function resetAreaVisibility(){document.querySelectorAll('#passport,.passport-actions,.dashboard-grid,.panel,.advanced-card').forEach(el=>el.classList.remove('hidden'));document.querySelectorAll('.paid-only-panel').forEach(el=>el.remove())}
function applyAdvancedState(d){const btn=$('#advancedBtn'),done=$('#advancedDone');if(!btn||!done)return;btn.classList.remove('hidden');btn.href='/acesso/prova-avancada';if(d?.advanced){btn.textContent='VER RESULTADO DA PROVA AVANÇADA';done.classList.remove('hidden');done.textContent=`Prova Avançada concluída: ${d.advanced.score}/100 • ${d.advanced.correctAnswers}/${d.advanced.totalQuestions} acertos`}else{btn.textContent='INICIAR PROVA AVANÇADA';done.classList.add('hidden');done.textContent=''}}
function renderPaidOnly(d){bundle=d;showOnly('area');resetAreaVisibility();['#passport','.passport-actions','.dashboard-grid','.panel'].forEach(sel=>document.querySelectorAll(sel).forEach(el=>el.classList.add('hidden')));const name=d.customerName||'Participante';$('#memberName').textContent=name;$('.welcome h1').innerHTML=`${esc(name)}, seu acesso está liberado.`;$('.welcome p').textContent='Pagamento confirmado. Sua Prova Avançada já está disponível.';const wrap=document.createElement('div');wrap.className='panel paid-only-panel';wrap.innerHTML='<div class="panel-title"><span>✓</span><div><small>COMPRA CONFIRMADA</small><h2>Seu acesso está ativo</h2></div></div><p class="muted">O e-mail da compra foi validado. Se você fez a primeira prova neste aparelho, volte ao resultado para vincular seu Certificado completo.</p><a class="cta" href="/acesso/prova-avancada">IR PARA A PROVA AVANÇADA</a>';$('#area').insertBefore(wrap,$('#logoutAccess'));applyAdvancedState(d)}
function render(d){bundle=d;resetAreaVisibility();const r=d.result||{};const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||d.customerName||'Participante';showOnly('area');$('.welcome h1').innerHTML=`<span id="memberName">${esc(name)}</span>, seu resultado completo está liberado.`;$('.welcome p').textContent='Seu Certificado e todas as entregas estão disponíveis abaixo.';$('#passportName').textContent=name;$('#passportLevel').textContent=`${icon} ${level}`;$('#passportScore').textContent=`${r.score||0}/100`;$('#passportCode').textContent=`#${r.proofCode||'—'}`;$('#scoreBig').textContent=`${r.score||0}/100`;$('#correctBig').textContent=`${r.correctAnswers||0}/${r.totalQuestions||10}`;$('#timeBig').textContent=`Tempo ${fmtTime(r.durationSeconds)}`;$('#scoreMeter').style.width=`${Math.max(0,Math.min(100,Number(r.score||0)))}%`;renderCategories(r.categoryStats||[]);renderAnswers(d.answers||[]);renderRoute(r.categoryStats||[]);applyAdvancedState(d)}
function renderCategories(stats){$('#categoryBars').innerHTML=stats.map(x=>`<div class="category-row"><span>${esc(x.category)}</span><div><i style="width:${Number(x.percent)||0}%"></i></div><b>${Number(x.percent)||0}%</b></div>`).join('')||'<p class="muted">Sem dados suficientes.</p>'}
function renderAnswers(list){$('#answerReview').innerHTML=list.map(x=>`<details class="review-item ${x.isCorrect?'good':'bad'}"><summary><span class="num">${x.position}</span><b>${esc(x.prompt)}</b><em>${x.isCorrect?'✓':'×'}</em></summary><div class="review-body"><p><strong>Sua resposta:</strong> ${esc(x.selectedLabel||x.selectedOption||'—')}</p>${x.isCorrect?'':`<p><strong>Resposta correta:</strong> ${esc(x.correctLabel||x.correctOption)}</p>`}<p>${esc(x.explanation)}</p>${x.referenceText?`<p class="ref">${esc(x.referenceText)}</p>`:''}</div></details>`).join('')}
function renderRoute(stats){const sorted=[...stats].sort((a,b)=>Number(a.percent)-Number(b.percent));const weak=sorted[0]?.category||'Fundamentos da Fé';const strong=[...stats].sort((a,b)=>Number(b.percent)-Number(a.percent))[0]?.category||'seus melhores temas';$('#routeIntro').textContent=`Seu ponto de atenção principal foi ${weak}. Sua maior força apareceu em ${strong}.`;const days=[['Diagnóstico',`Revise ${weak}.`],['Base doutrinal','Leia o gabarito comentado.'],['Memória ativa',`Escreva 5 pontos sobre ${weak} sem consultar.`],['Ensine para fixar',`Explique um conceito de ${weak} em voz alta.`],['Conecte com sua força',`Relacione ${weak} com ${strong}.`],['Revisão dos erros','Volte às questões que você errou.'],['Prova de evolução','Faça a Prova Avançada.']];$('#routeDays').innerHTML=days.map((x,i)=>`<div class="route-day"><b>DIA ${i+1}</b><div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div></div>`).join('')}
function drawPassport(){if(!bundle?.result)return;const r=bundle.result;const [level,icon]=levelFromScore(Number(r.score||0));const name=r.nickname||bundle.customerName||'Participante';const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d');const grad=ctx.createLinearGradient(0,0,1080,1350);grad.addColorStop(0,'#071c16');grad.addColorStop(1,'#174d37');ctx.fillStyle=grad;ctx.fillRect(0,0,1080,1350);ctx.strokeStyle='#d8b95b';ctx.lineWidth=4;ctx.strokeRect(48,48,984,1254);ctx.fillStyle='#58cc02';ctx.fillRect(70,70,120,120);ctx.fillStyle='#fff';ctx.font='900 62px system-ui';ctx.fillText('✠',96,152);ctx.fillStyle='#b9cbbf';ctx.font='700 27px system-ui';ctx.fillText('DESAFIO CATÓLICO RAIZ',230,108);ctx.fillStyle='#fff';ctx.font='900 38px system-ui';ctx.fillText('CERTIFICADO DE CONHECIMENTO',230,158);ctx.fillStyle='#e2b93b';ctx.font='800 25px system-ui';ctx.fillText('RESULTADO PERSONALIZADO • TEMPORADA FUNDADORES',70,300);ctx.fillStyle='#fff';ctx.font='900 68px system-ui';wrapText(ctx,name,70,405,930,78);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('NÍVEL ALCANÇADO',70,600);ctx.fillStyle='#fff';ctx.font='900 50px system-ui';ctx.fillText(`${icon} ${level}`,70,662);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('PONTUAÇÃO',70,770);ctx.fillStyle='#fff';ctx.font='900 66px system-ui';ctx.fillText(`${r.score||0}/100`,70,842);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('ACERTOS',530,770);ctx.fillStyle='#fff';ctx.font='900 54px system-ui';ctx.fillText(`${r.correctAnswers||0}/${r.totalQuestions||10}`,530,842);ctx.fillStyle='#9fb5ab';ctx.font='700 23px system-ui';ctx.fillText('CÓDIGO DA PROVA',70,955);ctx.fillStyle='#fff';ctx.font='900 45px system-ui';ctx.fillText(`#${r.proofCode||'—'}`,70,1014);ctx.fillStyle='#58cc02';ctx.fillRect(70,1130,940,4);ctx.fillStyle='#b9cbbf';ctx.font='700 24px system-ui';ctx.fillText('CERTIFICADO DIGITAL • CATÓLICO RAIZ',70,1200);ctx.fillStyle='#fff';ctx.font='700 21px system-ui';ctx.fillText('Resultado individual do Desafio Católico Raiz',70,1245);return c}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=String(text).split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=word+' ';y+=lineHeight}else line=test}ctx.fillText(line,x,y)}
$('#downloadPassport').addEventListener('click',()=>{const c=drawPassport();if(!c)return;const a=document.createElement('a');a.download='certificado-catolico-raiz.png';a.href=c.toDataURL('image/png');a.click()});
$('#sharePassport').addEventListener('click',async()=>{const c=drawPassport();if(!c)return;c.toBlob(async blob=>{try{const file=new File([blob],'certificado-catolico-raiz.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({title:'Meu Certificado Católico Raiz',text:'Este foi meu resultado no Desafio Católico Raiz.',files:[file]});else{await navigator.clipboard.writeText(location.origin);alert('Link copiado. Baixe seu Certificado e compartilhe junto!')}}catch{}},'image/png')});
$('#logoutAccess').addEventListener('click',()=>{localStorage.removeItem(ACCESS_TOKEN_KEY);localStorage.removeItem(BUNDLE_KEY);localStorage.removeItem(EMAIL_KEY);location.reload()});
(async()=>{const token=localStorage.getItem(ACCESS_TOKEN_KEY);if(token)return loadByToken(token);const email=localStorage.getItem(EMAIL_KEY);const attemptToken=getLastAttemptToken();if(email){showOnly('loading');let d=await linkEmailToAttempt(email,attemptToken);if(!d?.paid)d=await LCR_API.rpc('lcr_paid_delivery_by_email',{p_email:email},{retries:2}).catch(()=>null);if(d?.paid){saveBundle(d,email);return d.hasResult?render(d):renderPaidOnly(d)}}const cached=getCached();if(cached?.paid)return cached.hasResult?render(cached):renderPaidOnly(cached);showOnly('gate')})();