const $=s=>document.querySelector(s);let mode='login';
function setMode(next){mode=next;$('#authMessage').textContent='';document.querySelectorAll('#authTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#signupFields').classList.toggle('hidden',mode!=='signup');$('#confirmField').classList.toggle('hidden',mode!=='signup');$('#authTitle').textContent=mode==='signup'?'Crie sua conta':'Entre na sua conta';$('#authSubtitle').textContent=mode==='signup'?'Use o mesmo e-mail do quiz para recuperar seu progresso anterior.':'Acesse seu progresso, XP e posição no ranking.';$('#authSubmit').textContent=mode==='signup'?'CRIAR MINHA CONTA':'ENTRAR';$('#password').autocomplete=mode==='signup'?'new-password':'current-password'}
async function claimProfile(){const name=$('#name').value.trim(),nickname=$('#nickname').value.trim(),whatsapp=$('#whatsapp').value.trim();return LCR_API.rpc('lcr_claim_account',{p_season_slug:LCR_CONFIG.seasonSlug,p_name:name,p_nickname:nickname,p_whatsapp:whatsapp||null})}
$('#authTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(b)setMode(b.dataset.mode)});
$('#togglePassword').addEventListener('click',()=>{$('#password').type=$('#password').type==='password'?'text':'password'});
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value,password=$('#password').value;$('#authMessage').className='auth-message';$('#authMessage').textContent='';$('#authSubmit').disabled=true;$('#authSubmit').textContent='PROCESSANDO...';try{if(mode==='login'){await LCR_AUTH.signIn(email,password);location.href='/perfil'}else{if(password!==$('#confirmPassword').value)throw new Error('As senhas não são iguais.');const r=await LCR_AUTH.signUp({email,password,name:$('#name').value.trim(),nickname:$('#nickname').value.trim()});if(r.session){await claimProfile();location.href='/perfil'}else{$('#authMessage').classList.add('success');$('#authMessage').textContent='Conta criada! Abra seu e-mail para confirmar o cadastro e depois faça login.'}}}catch(err){$('#authMessage').classList.add('error');$('#authMessage').textContent=translateError(err.message)}finally{$('#authSubmit').disabled=false;$('#authSubmit').textContent=mode==='signup'?'CRIAR MINHA CONTA':'ENTRAR'}});
$('#forgotBtn').addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email){$('#authMessage').className='auth-message error';$('#authMessage').textContent='Digite seu e-mail primeiro.';return}try{await LCR_AUTH.recover(email);$('#authMessage').className='auth-message success';$('#authMessage').textContent='Enviamos um link de recuperação para seu e-mail.'}catch(e){$('#authMessage').className='auth-message error';$('#authMessage').textContent=translateError(e.message)}});
$('#savePassword').addEventListener('click',async()=>{try{await LCR_AUTH.updatePassword($('#newPassword').value);$('#authMessage').className='auth-message success';$('#authMessage').textContent='Senha atualizada! Redirecionando...';setTimeout(()=>location.href='/perfil',700)}catch(e){$('#authMessage').className='auth-message error';$('#authMessage').textContent=e.message}});
function translateError(m){const x=m.toLowerCase();if(x.includes('invalid login'))return'E-mail ou senha incorretos.';if(x.includes('email not confirmed'))return'Confirme seu e-mail antes de entrar.';if(x.includes('already registered')||x.includes('already been registered'))return'Este e-mail já possui uma conta.';if(x.includes('password'))return'A senha precisa ter pelo menos 8 caracteres.';return m}
(async()=>{const recovered=LCR_AUTH.consumeHashSession();if(recovered||new URLSearchParams(location.search).get('mode')==='recovery'){$('#authTabs').classList.add('hidden');$('#authForm').classList.add('hidden');$('#recoveryBox').classList.remove('hidden');$('#authTitle').textContent='Crie uma nova senha';$('#authSubtitle').textContent='Escolha uma senha segura para voltar à sua jornada.';return}if(await LCR_AUTH.getSession())location.href='/perfil';setMode('login')})();