const $=s=>document.querySelector(s);let mode='login',recoveryTimer=null;
const RECOVERY_COOLDOWN_KEY='lcr_recovery_cooldown_until';
function setMode(next){mode=next;$('#authMessage').textContent='';document.querySelectorAll('#authTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#signupFields').classList.toggle('hidden',mode!=='signup');$('#confirmField').classList.toggle('hidden',mode!=='signup');$('#authTitle').textContent=mode==='signup'?'Crie sua conta':'Entre na sua conta';$('#authSubtitle').textContent=mode==='signup'?'Use o mesmo e-mail do quiz para recuperar seu progresso anterior.':'Acesse seu progresso, XP e posição no ranking.';$('#authSubmit').textContent=mode==='signup'?'CRIAR MINHA CONTA':'ENTRAR';$('#password').autocomplete=mode==='signup'?'new-password':'current-password'}
async function claimProfile(){const name=$('#name').value.trim(),nickname=$('#nickname').value.trim(),whatsapp=$('#whatsapp').value.trim();return LCR_API.rpc('lcr_claim_account',{p_season_slug:LCR_CONFIG.seasonSlug,p_name:name,p_nickname:nickname,p_whatsapp:whatsapp||null})}
function setMessage(text,type=''){const el=$('#authMessage');el.className='auth-message'+(type?' '+type:'');el.textContent=text}
function startRecoveryCooldown(seconds=60){localStorage.setItem(RECOVERY_COOLDOWN_KEY,String(Date.now()+seconds*1000));refreshRecoveryCooldown()}
function refreshRecoveryCooldown(){clearInterval(recoveryTimer);const btn=$('#forgotBtn');const render=()=>{const until=Number(localStorage.getItem(RECOVERY_COOLDOWN_KEY)||0),remaining=Math.ceil((until-Date.now())/1000);if(remaining>0){btn.disabled=true;btn.textContent=`Aguarde ${remaining}s para reenviar`}else{btn.disabled=false;btn.textContent='Esqueci minha senha';localStorage.removeItem(RECOVERY_COOLDOWN_KEY);clearInterval(recoveryTimer)}};render();recoveryTimer=setInterval(render,1000)}
$('#authTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(b)setMode(b.dataset.mode)});
$('#togglePassword').addEventListener('click',()=>{$('#password').type=$('#password').type==='password'?'text':'password'});
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value,password=$('#password').value;setMessage('');$('#authSubmit').disabled=true;$('#authSubmit').textContent='PROCESSANDO...';try{if(mode==='login'){await LCR_AUTH.signIn(email,password);location.href='/profile.html'}else{if(password!==$('#confirmPassword').value)throw new Error('As senhas não são iguais.');const r=await LCR_AUTH.signUp({email,password,name:$('#name').value.trim(),nickname:$('#nickname').value.trim()});if(r.session){await claimProfile();location.href='/profile.html'}else{setMessage('Conta criada! Abra seu e-mail para confirmar o cadastro e depois faça login.','success')}}}catch(err){setMessage(translateError(err.message),'error')}finally{$('#authSubmit').disabled=false;$('#authSubmit').textContent=mode==='signup'?'CRIAR MINHA CONTA':'ENTRAR'}});
$('#forgotBtn').addEventListener('click',async()=>{const btn=$('#forgotBtn'),email=$('#email').value.trim();if(btn.disabled)return;if(!email){setMessage('Digite seu e-mail primeiro.','error');return}btn.disabled=true;btn.textContent='ENVIANDO...';try{await LCR_AUTH.recover(email);startRecoveryCooldown(60);setMessage('Enviamos um link de recuperação. Confira também a caixa de spam.','success')}catch(e){if(isEmailLimitError(e.message))startRecoveryCooldown(120);else{btn.disabled=false;btn.textContent='Esqueci minha senha'}setMessage(translateError(e.message),'error')}});
$('#savePassword').addEventListener('click',async()=>{try{await LCR_AUTH.updatePassword($('#newPassword').value);setMessage('Senha atualizada! Redirecionando...','success');setTimeout(()=>location.href='/profile.html',700)}catch(e){setMessage(translateError(e.message),'error')}});
function isEmailLimitError(m){const x=String(m||'').toLowerCase();return x.includes('email rate limit')||x.includes('over_email_send_rate_limit')||x.includes('only request this after')||x.includes('too many requests')}
function translateError(m){const x=String(m||'').toLowerCase();if(isEmailLimitError(m))return'O envio de e-mails está temporariamente no limite. Não clique novamente agora. Aguarde alguns minutos e tente de novo.';if(x.includes('invalid login'))return'E-mail ou senha incorretos.';if(x.includes('email not confirmed'))return'Confirme seu e-mail antes de entrar.';if(x.includes('already registered')||x.includes('already been registered'))return'Este e-mail já possui uma conta. Use a opção Entrar ou recupere sua senha.';if(x.includes('password'))return'A senha precisa ter pelo menos 8 caracteres.';return m||'Não foi possível concluir. Tente novamente.'}
(async()=>{refreshRecoveryCooldown();const recovered=LCR_AUTH.consumeHashSession();if(recovered||new URLSearchParams(location.search).get('mode')==='recovery'){$('#authTabs').classList.add('hidden');$('#authForm').classList.add('hidden');$('#recoveryBox').classList.remove('hidden');$('#authTitle').textContent='Crie uma nova senha';$('#authSubtitle').textContent='Escolha uma senha segura para voltar à sua jornada.';return}if(await LCR_AUTH.getSession())location.href='/profile.html';setMode('login')})();