const $=s=>document.querySelector(s);let quizData,attemptToken,startedAt,current=0,selected=null,secondsLeft=720,timerId,answers=[],hearts=5,submitting=false;
function show(id){['loading','start','quiz','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function tick(){secondsLeft--;$('#timer').textContent=fmt(Math.max(secondsLeft,0));if(secondsLeft<=0)finish()}
function saveLocal(){localStorage.setItem('lcr_current_attempt',JSON.stringify({attemptToken,startedAt,secondsLeft,hearts,current,answers}))}
function clearLocal(){localStorage.removeItem('lcr_current_attempt')}
async function init(){try{quizData=await LCR_API.rpc('lcr_get_quiz',{p_quiz_slug:LCR_CONFIG.quizSlug});const session=await LCR_AUTH.getSession();if(session){const d=await LCR_API.rpc('lcr_my_dashboard',{p_season_slug:LCR_CONFIG.seasonSlug});if(d.profile){document.querySelector('[name=name]').value=d.profile.name||'';document.querySelector('[name=nickname]').value=d.profile.nickname||'';document.querySelector('[name=email]').value=d.profile.email||'';document.querySelector('[name=whatsapp]').value=d.profile.whatsapp||'';document.querySelector('[name=email]').readOnly=true}}show('start')}catch(e){$('#loading').innerHTML=`<div class="mascot">!</div><h2>Não foi possível carregar</h2><p>${e.message}</p>`}}
$('#startForm').addEventListener('submit',async e=>{e.preventDefault();$('#startError').textContent='';const fd=new FormData(e.target);try{const session=await LCR_AUTH.getSession();const r=session?await LCR_API.rpc('lcr_start_attempt_for_user',{p_quiz_slug:LCR_CONFIG.quizSlug}):await LCR_API.rpc('lcr_start_attempt',{p_quiz_slug:LCR_CONFIG.quizSlug,p_name:fd.get('name'),p_nickname:fd.get('nickname'),p_email:fd.get('email'),p_whatsapp:fd.get('whatsapp')||null});attemptToken=r.attemptToken;if(r.alreadySubmitted){const old=await LCR_API.rpc('lcr_get_result',{p_attempt_token:attemptToken});return displayResult(old)}const progress=await LCR_API.rpc('lcr_get_attempt_progress',{p_attempt_token:attemptToken});answers=progress?.answers||[];current=answers.length;hearts=Math.max(0,5-answers.filter(x=>!x.isCorrect).length);startedAt=Date.now();secondsLeft=r.durationSeconds;$('#hearts').textContent=hearts;show('quiz');renderQuestion();timerId=setInterval(tick,1000);saveLocal()}catch(err){$('#startError').textContent=err.message}})
function renderQuestion(){if(current>=quizData.questions.length)return finish();selected=null;const q=quizData.questions[current];$('#category').textContent=q.category;$('#questionCount').textContent=`${current+1} de ${quizData.questions.length}`;$('#questionText').textContent=q.prompt;$('#progressBar').style.width=`${current/quizData.questions.length*100}%`;$('#feedback').classList.add('hidden');$('#checkBtn').classList.remove('hidden');$('#checkBtn').classList.add('disabled');$('#checkBtn').disabled=true;$('#options').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-key="${o.key}"><span>${String.fromCharCode(65+i)}</span><b>${escapeHtml(o.label)}</b></button>`).join('');$('#options').querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>{if($('#feedback').classList.contains('hidden')===false)return;selected=btn.dataset.key;$('#options').querySelectorAll('.answer-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#checkBtn').disabled=false;$('#checkBtn').classList.remove('disabled')}));window.scrollTo({top:0,behavior:'smooth'})}
$('#checkBtn').addEventListener('click',async()=>{if(!selected||submitting)return;submitting=true;$('#checkBtn').textContent='VERIFICANDO...';try{const q=quizData.questions[current];const r=await LCR_API.rpc('lcr_submit_answer',{p_attempt_token:attemptToken,p_question_id:q.id,p_selected_option_key:selected});answers.push(r);hearts=r.heartsRemaining;$('#hearts').textContent=hearts;$('#options').querySelectorAll('.answer-btn').forEach(btn=>{btn.disabled=true;if(btn.dataset.key===r.correctOption)btn.classList.add('correct');if(btn.dataset.key===selected&&!r.isCorrect)btn.classList.add('wrong')});$('#feedback').classList.remove('hidden');$('#feedback').classList.toggle('success',r.isCorrect);$('#feedback').classList.toggle('failure',!r.isCorrect);$('#feedbackIcon').textContent=r.isCorrect?'✓':'×';$('#feedbackTitle').textContent=r.isCorrect?'Muito bem!':'Quase lá!';$('#feedbackText').textContent=r.explanation||(`A resposta correta é ${r.correctOption}.`);$('#referenceText').textContent=r.referenceText||'';$('#checkBtn').classList.add('hidden');saveLocal()}catch(e){$('#quizError').textContent=e.message}finally{submitting=false;$('#checkBtn').textContent='VERIFICAR'}})
$('#continueBtn').addEventListener('click',()=>{current++;saveLocal();renderQuestion()});
async function finish(){if(submitting)return;submitting=true;clearInterval(timerId);try{const duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));const r=await LCR_API.rpc('lcr_finish_attempt',{p_attempt_token:attemptToken,p_duration_seconds:duration});clearLocal();displayResult(r)}catch(e){submitting=false;$('#quizError').textContent=e.message}}
function displayResult(r){show('result');const score=Number(r.score||0),xp=Math.round(score);$('#xp').textContent=xp;$('#accuracy').textContent=score+'%';$('#timeSpent').textContent=fmt(Number(r.durationSeconds||0));$('#resultTitle').textContent=score>=90?'Guardião da Fé!':score>=70?'Católico Raiz!':score>=50?'Boa jornada!':'Continue aprendendo!';$('#resultText').textContent=`Você acertou ${r.correctAnswers} de ${r.totalQuestions} desafios e ganhou ${xp} XP.`;$('#progressBar').style.width='100%';$('#hearts').textContent=Math.max(0,5-(r.totalQuestions-r.correctAnswers));window.scrollTo({top:0,behavior:'smooth'})}
$('#shareBtn').addEventListener('click',async()=>{const text=`Ganhei ${$('#xp').textContent} XP na Liga do Católico Raiz! Você consegue fazer melhor?`;if(navigator.share)await navigator.share({title:'Liga do Católico Raiz',text,url:location.origin});else{await navigator.clipboard.writeText(text+' '+location.origin);alert('Resultado copiado!')}})
$('#exitBtn').addEventListener('click',()=>{if(confirm('Deseja sair da lição? Seu progresso já respondido ficará salvo.'))location.href='/'});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();