const $=s=>document.querySelector(s);let quizData,attemptToken,startedAt,current=0,selected=null,secondsLeft=300,timerId,answers=[],hearts=5,submitting=false;
function show(id){['loading','start','quiz','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function tick(){secondsLeft--;$('#timer').textContent=fmt(Math.max(secondsLeft,0));if(secondsLeft<=0)finish()}
function saveLocal(){localStorage.setItem('lcr_current_attempt',JSON.stringify({attemptToken,startedAt,secondsLeft,hearts,current,answers}))}
function clearLocal(){localStorage.removeItem('lcr_current_attempt')}
async function init(){try{quizData=await LCR_API.rpc('lcr_get_quiz',{p_quiz_slug:LCR_CONFIG.quizSlug});show('start')}catch(e){$('#loading').innerHTML=`<div class="mascot">!</div><h2>Não foi possível carregar</h2><p>${escapeHtml(e.message)}</p>`}}
$('#startForm').addEventListener('submit',async e=>{e.preventDefault();$('#startError').textContent='';const fd=new FormData(e.target);const btn=e.submitter||e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='PREPARANDO...';try{const r=await LCR_API.rpc('lcr_start_attempt_quick',{p_quiz_slug:LCR_CONFIG.quizSlug,p_display_name:fd.get('name'),p_whatsapp:fd.get('whatsapp')});attemptToken=r.attemptToken;if(r.alreadySubmitted){return routeResult()}const progress=await LCR_API.rpc('lcr_get_attempt_progress',{p_attempt_token:attemptToken});answers=progress?.answers||[];current=answers.length;hearts=Math.max(0,5-answers.filter(x=>!x.isCorrect).length);startedAt=Date.now();secondsLeft=r.durationSeconds||300;$('#hearts').textContent=hearts;$('#timer').textContent=fmt(secondsLeft);show('quiz');renderQuestion();timerId=setInterval(tick,1000);saveLocal()}catch(err){$('#startError').textContent=err.message;btn.disabled=false;btn.textContent='COMEÇAR O DESAFIO'}})
function renderQuestion(){if(current>=quizData.questions.length)return finish();selected=null;const q=quizData.questions[current];$('#category').textContent=q.category;$('#questionCount').textContent=`${current+1} de ${quizData.questions.length}`;$('#questionText').textContent=q.prompt;$('#progressBar').style.width=`${current/quizData.questions.length*100}%`;$('#feedback').classList.add('hidden');$('#feedback').classList.remove('success','failure');$('#checkBtn').classList.remove('hidden');$('#checkBtn').classList.add('disabled');$('#checkBtn').disabled=true;$('#options').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-key="${o.key}"><span>${String.fromCharCode(65+i)}</span><b>${escapeHtml(o.label)}</b></button>`).join('');$('#options').querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>{if(!$('#feedback').classList.contains('hidden'))return;selected=btn.dataset.key;$('#options').querySelectorAll('.answer-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#checkBtn').disabled=false;$('#checkBtn').classList.remove('disabled')}));window.scrollTo({top:0,behavior:'smooth'})}
$('#checkBtn').addEventListener('click',async()=>{if(!selected||submitting)return;submitting=true;$('#checkBtn').textContent='VERIFICANDO...';try{const q=quizData.questions[current];const r=await LCR_API.rpc('lcr_submit_answer',{p_attempt_token:attemptToken,p_question_id:q.id,p_selected_option_key:selected});answers.push(r);hearts=r.heartsRemaining;$('#hearts').textContent=hearts;$('#options').querySelectorAll('.answer-btn').forEach(btn=>{btn.disabled=true;if(btn.dataset.key===r.correctOption)btn.classList.add('correct');if(btn.dataset.key===selected&&!r.isCorrect)btn.classList.add('wrong')});$('#feedback').classList.remove('hidden');$('#feedback').classList.toggle('success',r.isCorrect);$('#feedback').classList.toggle('failure',!r.isCorrect);$('#feedbackIcon').textContent=r.isCorrect?'✓':'×';$('#feedbackTitle').textContent=r.isCorrect?randomPraise():randomEncouragement();$('#feedbackText').textContent=r.explanation||(`A resposta correta é ${r.correctOption}.`);$('#referenceText').textContent=r.referenceText||'';$('#checkBtn').classList.add('hidden');saveLocal()}catch(e){$('#quizError').textContent=e.message}finally{submitting=false;$('#checkBtn').textContent='VERIFICAR'}})
$('#continueBtn').addEventListener('click',()=>{current++;saveLocal();renderQuestion()});
async function finish(){if(submitting)return;submitting=true;clearInterval(timerId);show('result');try{const duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));await LCR_API.rpc('lcr_finish_attempt',{p_attempt_token:attemptToken,p_duration_seconds:duration});clearLocal();await routeResult()}catch(e){submitting=false;show('quiz');$('#quizError').textContent=e.message}}
async function routeResult(){show('result');const routed=await LCR_API.rpc('lcr_route_result',{p_attempt_token:attemptToken});sessionStorage.setItem('lcr_last_result',JSON.stringify(routed));setTimeout(()=>{location.href=`${routed.pagePath}?t=${encodeURIComponent(attemptToken)}`},700)}
function randomPraise(){const a=['Boa! +10 XP','Mandou bem!','Acertou em cheio!','Sequência mantida!','Isso é Católico Raiz!'];return a[Math.floor(Math.random()*a.length)]}
function randomEncouragement(){const a=['Quase!','Boa tentativa!','Agora você não esquece!','Essa pegou muita gente!'];return a[Math.floor(Math.random()*a.length)]}
$('#exitBtn').addEventListener('click',()=>{if(confirm('Deseja sair do desafio? As respostas já enviadas ficam registradas.'))location.href='/'});
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
init();