const $=s=>document.querySelector(s);let quizData,attemptToken,startedAt,current=0,selected=null,secondsLeft=300,timerId,answers=[],hearts=5,submitting=false;
const quizDataPromise=loadQuizData();
function show(id){['loading','start','quiz','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function tick(){secondsLeft--;$('#timer').textContent=fmt(Math.max(secondsLeft,0));if(secondsLeft<=0)finish()}
function saveLocal(){localStorage.setItem('lcr_current_attempt',JSON.stringify({attemptToken,startedAt,secondsLeft,hearts,current,answers}))}
function clearLocal(){localStorage.removeItem('lcr_current_attempt')}
function haptic(pattern){try{if('vibrate'in navigator)navigator.vibrate(pattern)}catch{}}
function emotionalProgress(index,total){const remaining=total-index-1;if(index===0)return'Valendo!';if(index===1)return'Bom começo';if(index===2)return'Pegando ritmo';if(index===3)return'Quase na metade';if(index===4)return'Metade!';if(remaining===4)return'Mais da metade';if(remaining===3)return'Faltam 4';if(remaining===2)return'Reta final';if(remaining===1)return'Só mais 2';if(remaining===0)return'Última pergunta';return'Continue firme'}
function focusQuestion(){requestAnimationFrame(()=>{const quiz=$('#quiz');if(!quiz)return;const y=Math.max(0,quiz.getBoundingClientRect().top+window.scrollY-58);window.scrollTo({top:y,behavior:'smooth'})})}
function fitQuestionToViewport(){document.body.classList.remove('quiz-tight','quiz-ultra');requestAnimationFrame(()=>{const btn=$('#checkBtn');if(!btn||btn.classList.contains('hidden'))return;const limit=window.innerHeight-Math.max(8,parseInt(getComputedStyle(document.documentElement).getPropertyValue('--sab')||'8',10));if(btn.getBoundingClientRect().bottom>limit){document.body.classList.add('quiz-tight');requestAnimationFrame(()=>{if(btn.getBoundingClientRect().bottom>window.innerHeight-6)document.body.classList.add('quiz-ultra')})}})}
function trackQuizStart(){try{if(!sessionStorage.getItem('lcr_meta_lead_sent')){window.LCR_TRACK?.track('Lead',{content_name:'Desafio Católico Raiz'});sessionStorage.setItem('lcr_meta_lead_sent','1')}window.LCR_TRACK?.custom('QuizStarted',{quiz_slug:LCR_CONFIG.quizSlug,season:LCR_CONFIG.seasonSlug})}catch{}}
function trackQuizComplete(result){try{const key=`lcr_meta_complete_${attemptToken}`;if(sessionStorage.getItem(key))return;const params={content_name:'Desafio Católico Raiz',score:Number(result?.score||0),correct_answers:Number(result?.correctAnswers||0),total_questions:Number(result?.totalQuestions||10),segment:String(result?.routeSlug||result?.resultRouteSlug||'')};window.LCR_TRACK?.track('CompleteRegistration',params);window.LCR_TRACK?.custom('QuizCompleted',params);sessionStorage.setItem(key,'1')}catch{}}
async function loadQuizData(){try{const r=await fetch('/quiz-data.v1.json',{cache:'force-cache'});if(!r.ok)throw new Error('Quiz indisponível');return await r.json()}catch{return LCR_API.rpc('lcr_get_quiz',{p_quiz_slug:LCR_CONFIG.quizSlug},{retries:2})}}
async function beginAttempt(token,duration=300,progressAnswers=[],serverStartedAt=null){quizData=quizData||await quizDataPromise;attemptToken=token;answers=Array.isArray(progressAnswers)?progressAnswers:[];current=answers.length;hearts=Math.max(0,5-answers.filter(x=>!x.isCorrect).length);const parsed=serverStartedAt?Date.parse(serverStartedAt):NaN;startedAt=Number.isFinite(parsed)?parsed:Date.now();const elapsed=Math.max(0,Math.floor((Date.now()-startedAt)/1000));secondsLeft=Math.max(0,(duration||300)-elapsed);$('#hearts').textContent=hearts;$('#timer').textContent=fmt(secondsLeft);if(secondsLeft<=0)return finish();show('quiz');renderQuestion();clearInterval(timerId);timerId=setInterval(tick,1000);saveLocal()}
async function init(){const retryToken=new URLSearchParams(location.search).get('retry');if(retryToken){try{quizData=await quizDataPromise;history.replaceState({},'',location.pathname);return beginAttempt(retryToken,300,[],null)}catch(e){return showLoadError(e)}}show('start');quizDataPromise.then(x=>{quizData=x}).catch(()=>{})}
function showLoadError(e){$('#loading').innerHTML=`<div class="mascot">!</div><h2>Não foi possível carregar</h2><p>${escapeHtml(e.message)}</p>`;show('loading')}
$('#startForm').addEventListener('submit',async e=>{e.preventDefault();$('#startError').textContent='';const fd=new FormData(e.target);const btn=e.submitter||e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='PREPARANDO...';try{quizData=quizData||await quizDataPromise;const r=await LCR_API.rpc('lcr_start_attempt_quick',{p_quiz_slug:LCR_CONFIG.quizSlug,p_display_name:fd.get('name'),p_whatsapp:fd.get('whatsapp')});attemptToken=r.attemptToken;trackQuizStart();if(r.alreadySubmitted)return finishAndRoute(0);await beginAttempt(attemptToken,r.durationSeconds||300,r.answers||[],r.startedAt||null)}catch(err){$('#startError').textContent=humanError(err.message);btn.disabled=false;btn.textContent='COMEÇAR O DESAFIO'}})
function renderQuestion(){if(current>=quizData.questions.length)return finish();selected=null;const q=quizData.questions[current],total=quizData.questions.length;$('#category').textContent=q.category;$('#questionCount').textContent=`${current+1} de ${total} · ${emotionalProgress(current,total)}`;$('#questionText').textContent=q.prompt;$('#progressBar').style.width=`${current/total*100}%`;$('#feedback').classList.add('hidden');$('#feedback').classList.remove('success','failure');$('#checkBtn').classList.remove('hidden');$('#checkBtn').classList.add('disabled');$('#checkBtn').disabled=true;$('#options').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-key="${o.key}"><span>${String.fromCharCode(65+i)}</span><b>${escapeHtml(o.label)}</b></button>`).join('');$('#options').querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>{if(!$('#feedback').classList.contains('hidden'))return;selected=btn.dataset.key;haptic(8);$('#options').querySelectorAll('.answer-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#checkBtn').disabled=false;$('#checkBtn').classList.remove('disabled')}));focusQuestion();fitQuestionToViewport()}
$('#checkBtn').addEventListener('click',async()=>{if(!selected||submitting)return;submitting=true;$('#quizError').textContent='';$('#checkBtn').textContent='VERIFICANDO...';try{const q=quizData.questions[current];const r=await LCR_API.rpc('lcr_submit_answer',{p_attempt_token:attemptToken,p_question_id:q.id,p_selected_option_key:selected});answers.push(r);hearts=r.heartsRemaining;$('#hearts').textContent=hearts;$('#options').querySelectorAll('.answer-btn').forEach(btn=>{btn.disabled=true;if(btn.dataset.key===r.correctOption)btn.classList.add('correct');if(btn.dataset.key===selected&&!r.isCorrect)btn.classList.add('wrong')});$('#feedback').classList.remove('hidden');$('#feedback').classList.toggle('success',r.isCorrect);$('#feedback').classList.toggle('failure',!r.isCorrect);$('#feedbackIcon').textContent=r.isCorrect?'✓':'×';$('#feedbackTitle').textContent=r.isCorrect?randomPraise():randomEncouragement();$('#feedbackText').textContent=r.explanation||(`A resposta correta é ${r.correctOption}.`);$('#referenceText').textContent=r.referenceText||'';$('#checkBtn').classList.add('hidden');r.isCorrect?haptic(35):haptic([45,35,45]);saveLocal();requestAnimationFrame(()=>$('#feedback').scrollIntoView({behavior:'smooth',block:'end'}))}catch(e){if(String(e.message).toLowerCase().includes('tempo encerrado')){submitting=false;return finish()}$('#quizError').textContent=humanError(e.message)}finally{submitting=false;$('#checkBtn').textContent='VERIFICAR'}})
$('#continueBtn').addEventListener('click',()=>{haptic(8);current++;saveLocal();renderQuestion()});
window.addEventListener('resize',()=>{if(!$('#quiz')?.classList.contains('hidden'))fitQuestionToViewport()},{passive:true});
async function finish(){if(submitting)return;submitting=true;clearInterval(timerId);show('result');try{const duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));clearLocal();await finishAndRoute(duration)}catch(e){submitting=false;show('quiz');$('#quizError').textContent=humanError(e.message)}}
async function finishAndRoute(duration){show('result');const packed=await LCR_API.rpc('lcr_finish_and_route',{p_attempt_token:attemptToken,p_duration_seconds:duration});if(packed?.result){sessionStorage.setItem('lcr_last_result',JSON.stringify({token:attemptToken,data:packed.result,route:packed}));trackQuizComplete({...packed.result,routeSlug:packed.routeSlug})}location.href=`${packed.pagePath}?t=${encodeURIComponent(attemptToken)}`}
function randomPraise(){const a=['Boa! +10 XP','Mandou bem!','Acertou em cheio!','Sequência mantida!','Isso é Católico Raiz!'];return a[Math.floor(Math.random()*a.length)]}
function randomEncouragement(){const a=['Quase!','Boa tentativa!','Agora você não esquece!','Essa pegou muita gente!'];return a[Math.floor(Math.random()*a.length)]}
function humanError(m){const x=String(m||'');if(/failed to fetch|network|conexão demorou/i.test(x))return'Sua internet oscilou. Tentamos reconectar automaticamente. Toque novamente.';return x||'Não foi possível concluir. Tente novamente.'}
$('#exitBtn').addEventListener('click',()=>{if(confirm('Deseja sair do desafio? As respostas já enviadas ficam registradas.'))location.href='/'});
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();